apiVersion: opencontext.com/v1alpha1
kind: Component
metadata:
  name: sandbox
  annotations:
    github.com/project-slug: opencontextinc/sandbox
spec:
  type: other
  lifecycle: unknown
  otherType: repo
